#!/usr/bin/env python3
"""Builds a fully offline, dependency-free copy of the app into offline/ -
no ES modules, no fetch(), nothing that requires a local server: just
double-click offline/index.html (via file://) in any modern browser, so it
can be copied to a USB drive and run on a computer with no internet access.

How it works:
  - Every js/**/*.js module is concatenated into one plain <script> (no
    type="module"), in dependency order. `export` is stripped (everything
    becomes a normal top-level declaration in one shared scope - verified
    there are no name collisions across modules) and `import {a,b} from`
    lines are dropped entirely, since after flattening the names already
    exist. `import * as X from '...'` becomes a generated `const X = {...}`
    object built from that module's own export names.
  - The four data/*.json lookup tables are inlined as JS constants and
    data-loader.js's fetch()-based loadTables() is replaced with a version
    that just returns them directly - fetch() of local files is blocked
    under file:// in most browsers, same reason ES modules are.
  - assets/ is copied alongside index.html (plain <img src="..."> to a
    relative file works fine under file://, unlike fetch/modules). The
    Hebrew webfont is the exception: a font file is subject to CORS even
    from file://, so it's inlined into the CSS as a data: URI instead.
  - The favicon and home screen icon links come out. They are site absolute
    (/icons/...), which under file:// points at the root of the disk, and a
    web manifest cannot be fetched from file:// at all: Chrome logs an error
    for it. None of it means anything for a folder on a stick anyway.

Re-run this any time the js/ source changes to refresh offline/.
"""
import base64
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
JS_DIR = ROOT / "js"
OUT_DIR = ROOT / "offline"
ENTRY = "app.js"
JS_MAP_MARKER = "<!-- js version map: generated by build-offline.py, do not edit by hand -->"

# Where the site lives, in one place.
#
# A sitemap, a canonical link and the structured data all have to name the site with a
# whole address rather than a path, so the domain would otherwise be written into four
# files and would have to be found in all four the day it changes. It is written here
# instead and stamped in from here, so moving the site to a domain of the shul's own is
# this line and a rebuild. No trailing slash.
SITE_URL = "https://lczmanim.cjaffa.com"
SITE_URL_MARKER = "<!-- site address: stamped by build-offline.py from SITE_URL, do not edit by hand -->"

# The three pages behind the menu, and the addresses they answer at.
#
# They used to be hashes on the one address, and a hash never reaches a server: /#week and
# /#donate arrived at a crawler as the same blank page, so the whole site was one entry
# with one title, and searching for the shul's zmanim found a page whose title said
# nothing about zmanim. Each of these becomes a real folder with a real index.html, which
# is what a static host needs in place of a rewrite rule.
#
# Written out of index.html rather than typed here, so the head only exists once: the
# icons, the manifest, the stamped stylesheet links and the import map are all things
# that would otherwise be copied into four files and would drift apart the first time one
# of them changed. Only the parts that differ per page are below.
#
# The blurb is what a search result shows under the title, and what a crawler reads if it
# never runs the JavaScript. It is a description of the page, not a slogan: the words
# somebody would actually type are the times, the days, the season, the shul's name.
ROUTES = {
    "week": {
        "title": "Weekly Zmanim",
        "description": (
            "This week's davening times and zmanim for Bais Medrash of Lakewood Commons, "
            "44 Coles Way, Lakewood NJ: shacharis, mincha, maariv, candle lighting and "
            "the Shabbos schedule."
        ),
        "heading": "Weekly Zmanim",
        "blurb": (
            "The week's minyanim and zmanim at Bais Medrash of Lakewood Commons: shacharis, "
            "mincha and maariv, candle lighting for Shabbos, and the day's zmanim worked "
            "from the shul's own location."
        ),
    },
    "chart": {
        "title": "Zmanim chart",
        "description": (
            "The printable season zmanim chart for Bais Medrash of Lakewood Commons, "
            "44 Coles Way, Lakewood NJ: every week of the season on one page, Shabbos and "
            "weekday."
        ),
        "heading": "Zmanim chart",
        "blurb": (
            "The season's zmanim board, laid out week by week and made to be printed: the "
            "Shabbos chart and the weekday chart for Bais Medrash of Lakewood Commons."
        ),
    },
    "donate": {
        "title": "Donate",
        "description": (
            "Ways to give to Bais Medrash of Lakewood Commons, 44 Coles Way, Lakewood NJ: "
            "credit card, ACH, Zelle and The Donors' Fund. Tax ID 26-4527675."
        ),
        "heading": "Donate",
        "blurb": (
            "Ways to support Bais Medrash of Lakewood Commons: by card or ACH, by Zelle, or "
            "through The Donors' Fund. Tax ID 26-4527675."
        ),
    },
}

EXPORT_FUNC_RE = re.compile(r"^export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)", re.M)
EXPORT_CONST_RE = re.compile(r"^export\s+const\s+([A-Za-z0-9_]+)", re.M)
IMPORT_NAMED_RE = re.compile(r"^import\s*\{[^}]*\}\s*from\s*['\"][^'\"]+['\"];?\s*$", re.M)
IMPORT_STAR_RE = re.compile(r"^import\s*\*\s*as\s+([A-Za-z0-9_]+)\s*from\s*['\"]([^'\"]+)['\"];?\s*$", re.M)


def all_js_files():
    return sorted(JS_DIR.rglob("*.js"))


def rel_key(path: Path) -> str:
    return path.relative_to(JS_DIR).as_posix()


def resolve_import(from_file: Path, spec: str) -> str:
    resolved = (from_file.parent / spec).resolve()
    return rel_key(resolved)


def export_names(text: str) -> list:
    return EXPORT_FUNC_RE.findall(text) + EXPORT_CONST_RE.findall(text)


def build_dep_graph(files):
    texts = {rel_key(f): f.read_text(encoding="utf-8") for f in files}
    deps = {}
    for key, text in texts.items():
        f = JS_DIR / key
        d = set()
        for m in IMPORT_NAMED_RE.finditer(text):
            spec = re.search(r"from\s*['\"]([^'\"]+)['\"]", m.group(0)).group(1)
            d.add(resolve_import(f, spec))
        for m in IMPORT_STAR_RE.finditer(text):
            d.add(resolve_import(f, m.group(2)))
        deps[key] = d
    return texts, deps


def topo_sort(deps):
    order = []
    visited = set()
    temp = set()

    def visit(key):
        if key in visited:
            return
        if key in temp:
            raise RuntimeError(f"circular dependency at {key}")
        temp.add(key)
        for d in sorted(deps.get(key, [])):
            visit(d)
        temp.discard(key)
        visited.add(key)
        order.append(key)

    for key in sorted(deps):
        visit(key)
    return order


def transform_module(key, text, all_exports):
    # Record namespace-import requests, then strip all import lines.
    namespace_consts = []
    for m in IMPORT_STAR_RE.finditer(text):
        local_name, spec = m.group(1), m.group(2)
        target = resolve_import(JS_DIR / key, spec)
        names = all_exports[target]
        namespace_consts.append(f"const {local_name} = {{ {', '.join(names)} }};")
    text = IMPORT_STAR_RE.sub("", text)
    text = IMPORT_NAMED_RE.sub("", text)
    # Strip the `export ` keyword, leaving the declaration itself.
    text = re.sub(r"^export\s+(?=(async\s+)?function\s)", "", text, flags=re.M)
    text = re.sub(r"^export\s+(?=const\s)", "", text, flags=re.M)
    # Only the two declaration forms above are understood. A bare `export { a, b }` is
    # left standing by both, and a stray export keyword in a plain script is a syntax
    # error that takes the whole offline app down with nothing on screen to say why. It
    # cost a build that looked fine and came up blank, so it is caught here instead: put
    # the name in one module and import it, rather than re-exporting it from a second.
    leftover = re.search(r"^export\s*[{*]", text, flags=re.M)
    if leftover:
        raise RuntimeError(
            f"offline build: {key} has a re-export the flattener cannot strip "
            f"({leftover.group(0).strip()!r}). Import the name from where it is declared."
        )
    return text.strip("\n"), namespace_consts


TOP_LEVEL_DECL_RE = re.compile(r"^(?:export\s+)?(const|let|var|function|class)\s+([A-Za-z_$][\w$]*)", re.M)


def check_name_collisions(bundled_keys, texts):
    """Two modules declaring the same top-level name.

    Under ES modules each file has its own scope, so this is perfectly legal and the
    hosted site never notices. Flattened into one script it is a SyntaxError, and the
    whole bundle fails to parse: the USB copy opens to a blank page while the site it
    was built from carries on working. That is exactly how it went unnoticed for six
    days, so it is checked here rather than asserted in a comment.

    Only a repeated `function` is allowed, which is a legal redeclaration - several
    modules have their own private `esc` helper and always have. Anything involving a
    const, let, var or class stops the build.
    """
    seen = {}
    problems = []
    for key in bundled_keys:
        for m in TOP_LEVEL_DECL_RE.finditer(texts[key]):
            # Column 0 only: an indented match is inside some other function.
            if m.start() and texts[key][m.start() - 1] != "\n":
                continue
            kind, name = m.group(1), m.group(2)
            if name in seen:
                prev_kind, prev_key = seen[name]
                if not (kind == "function" and prev_kind == "function"):
                    problems.append(f"  {name}: {prev_kind} in {prev_key}, {kind} in {key}")
            else:
                seen[name] = (kind, key)
    if problems:
        raise SystemExit(
            "offline build: the same top-level name is declared in two modules, which the\n"
            "flattened bundle cannot parse. Rename one of each pair (or move it to a module\n"
            "both import):\n" + "\n".join(problems)
        )


def build_data_loader_replacement():
    tables = {}
    for name, filename in [
        ("parshaChutz", "parsha_chutz.json"),
        ("parshaEY", "parsha_ey.json"),
        ("parshaNames", "parsha_names.json"),
        ("specialDays", "special_days.json"),
    ]:
        tables[name] = json.loads((ROOT / "data" / filename).read_text(encoding="utf-8"))
    lines = ["// --- inlined data/*.json (offline build: fetch() of local files is blocked under file://) ---"]
    for name, data in tables.items():
        lines.append(f"const __TABLE_{name} = {json.dumps(data, ensure_ascii=False)};")
    lines.append("let cached = null;")
    lines.append("async function loadTables() {")
    lines.append("  if (cached) return cached;")
    lines.append("  cached = { parshaChutz: __TABLE_parshaChutz, parshaEY: __TABLE_parshaEY, parshaNames: __TABLE_parshaNames, specialDays: __TABLE_specialDays };")
    lines.append("  return cached;")
    lines.append("}")
    return "\n".join(lines)


def inline_fonts(css: str) -> str:
    """Replace url(../assets/fonts/x.woff2) with a base64 data: URI.

    Chrome treats a font fetched from file:// as cross-origin and refuses to use it, so
    the copied .woff2 files would be ignored in exactly the offline case they exist for.
    A data: URI is part of the stylesheet itself, so there is no fetch to block. The two
    Hebrew subsets are ~25KB total, small enough that inlining costs nothing.
    """

    def sub(match):
        path = ROOT / "assets" / "fonts" / match.group(1)
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        return f"url('data:font/woff2;base64,{b64}')"

    return re.sub(r"url\('\.\./assets/fonts/([\w.-]+)'\)", sub, css)


def stamp_css_versions(page: Path, prefix: str):
    """Rewrite a page's stylesheet links to css/x.css?v=<hash of that file>.

    GitHub Pages serves everything with a 10-minute max-age, so after a deploy the
    browser keeps showing the previous stylesheet until it expires - a design change
    looks like it simply didn't ship. The hash changes only when the CSS does, so the
    new URL is fetched immediately while an unchanged file stays cached.

    See stamp_js_versions() for the modules, which need a different mechanism.
    """
    html = page.read_text(encoding="utf-8")

    def stamp(match):
        name = match.group(1)
        digest = hashlib.md5((ROOT / "css" / name).read_bytes()).hexdigest()[:8]
        return f'href="{prefix}css/{name}?v={digest}"'

    stamped = re.sub(r'href="(?:\.\./)?css/([\w.-]+\.css)(?:\?v=[0-9a-f]+)?"', stamp, html)
    if stamped != html:
        page.write_text(stamped, encoding="utf-8", newline="\n")


def stamp_site_url(page: Path):
    """Write the whole-address tags into the page head, from SITE_URL.

    Three things need the site named with a scheme and a host rather than a path: the
    canonical link, og:url, and the url in the structured data. Written between the
    markers so the block can be replaced wholesale on the next run, the same way the
    import map is.

    The canonical matters more here than it looks. Every view of this site is one URL
    with a different hash on the end, and a hash never reaches a server, so #week and
    #donate are the same page as far as a crawler is concerned. Saying which address is
    the real one keeps a shared link with a stray query string or a tracking tag on it
    from being counted as a second copy of the same page.
    """
    html = page.read_text(encoding="utf-8")
    block = f"""{SITE_URL_MARKER}
<link rel="canonical" href="{SITE_URL}/">
<meta property="og:url" content="{SITE_URL}/">
<meta property="og:image" content="{SITE_URL}/assets/shul-1400.jpg">
<meta property="og:image:alt" content="Bais Medrash of Lakewood Commons, 44 Coles Way, Lakewood">"""
    pattern = re.escape(SITE_URL_MARKER) + r'\n(?:<link rel="canonical".*?>\n|<meta property="og:(?:url|image|image:alt)".*?>\n)*'
    if SITE_URL_MARKER in html:
        html = re.sub(pattern, block + "\n", html, flags=re.S)
    else:
        html = html.replace("</head>", block + "\n</head>")
    # The picture named in the structured data, which wants a whole address too. Written in
    # the page as a plain path so it reads as one, and given its host here so the domain is
    # still only spelled out in this file. The optional host in the pattern is what makes a
    # second run replace rather than double up.
    html = re.sub(
        r'("image":\s*")(?:https?://[^"]*)?(/assets/[^"]+")',
        lambda m: m.group(1) + SITE_URL + m.group(2),
        html,
    )
    page.write_text(html, encoding="utf-8", newline="\n")


def write_route_pages():
    """Write /week/index.html, /chart/index.html and /donate/index.html.

    Each one is index.html with five things changed: the title, the description, the two
    og: lines that mirror them, the address it says is its own, and the plain-HTML shell
    inside <main>. Everything else - the icons, the manifest, the theme colour, the
    stamped stylesheet links, the import map, the module entry - comes across untouched,
    which is the point of deriving them rather than keeping four hand-written files that
    have to be remembered together.

    Run after the stamping, so the hashes these inherit are the ones just written.

    Two things have to be rewritten on the way, both because the file has moved down a
    folder. The relative paths (css/, js/, vendor/) are made site-absolute, or a browser
    at /week/ asks for /week/css/app.css and gets a 404. And the structured data comes
    out: it is one record describing one building, and repeating it on four addresses
    invites a search engine to believe in four buildings. It stays on the menu, which is
    the address the canonical tags here all point back to for the site as a whole.
    """
    src = (ROOT / "index.html").read_text(encoding="utf-8")
    for name, meta in ROUTES.items():
        html = src
        # Down one folder: every path that was relative to the root has to say so.
        html = re.sub(r'(href|src)="(css/|js/|vendor/)', r'\1="/\2', html)
        full_title = f"{meta['title']} &middot; Bais Medrash of Lakewood Commons"
        html = re.sub(r"<title>.*?</title>", f"<title>{full_title}</title>", html, flags=re.S)
        html = re.sub(
            r'(<meta name="description" content=")[^"]*(">)',
            lambda m: m.group(1) + meta["description"] + m.group(2),
            html,
        )
        html = re.sub(
            r'(<meta property="og:title" content=")[^"]*(">)',
            lambda m: m.group(1) + full_title + m.group(2),
            html,
        )
        html = re.sub(
            r'(<meta property="og:description" content=")[^"]*(">)',
            lambda m: m.group(1) + meta["description"] + m.group(2),
            html,
        )
        html = html.replace(f'href="{SITE_URL}/"', f'href="{SITE_URL}/{name}/"')
        html = html.replace(f'content="{SITE_URL}/"', f'content="{SITE_URL}/{name}/"')
        # The one record of the place stays on the menu page.
        html = re.sub(
            r'<script type="application/ld\+json">.*?</script>\n', "", html, flags=re.S
        )
        html = re.sub(
            r"<main id=\"main\">.*?</main>", route_shell(name, meta), html, flags=re.S
        )
        # Every one of the substitutions above is a regex against a file this script does
        # not own, and a regex that matches nothing fails quietly: the page would still be
        # written, and it would be the menu again under a second address, which is worse
        # than not having the page at all. So each thing that had to change is asked for
        # afterwards. If index.html is restructured, this stops the build rather than
        # shipping four copies of one page.
        for what, needle in [
            ("the title", f"<title>{full_title}</title>"),
            ("the description", meta["description"]),
            ("its own address", f"{SITE_URL}/{name}/"),
            ("the shell", f'<h1 class="luach-bar-title">{meta["heading"]}</h1>'),
        ]:
            if needle not in html:
                raise RuntimeError(f"/{name}/: {what} did not take (index.html changed shape?)")
        if 'href="css/' in html or 'src="js/' in html or 'src="vendor/' in html:
            raise RuntimeError(f"/{name}/: a path was left relative and would 404 a folder down")
        if "application/ld+json" in html:
            raise RuntimeError(f"/{name}/: the structured data was left in")
        # Inherited from index.html rather than written here, so it is worth checking it
        # actually came across: a route page that can be machine translated is the bug
        # these were added for, and it would show on the page a donation is made from.
        if 'translate="no"' not in html or 'content="notranslate"' not in html:
            raise RuntimeError(f"/{name}/: the do-not-translate markers did not come across")
        out = ROOT / name
        out.mkdir(exist_ok=True)
        (out / "index.html").write_text(html, encoding="utf-8", newline="\n")


def route_shell(name: str, meta: dict) -> str:
    """The page as it is served, before the app has run - the route's own version.

    Same job as the shell in index.html and built out of the same classes: a crawler that
    never runs the JavaScript, and a visitor who has it turned off, should still find the
    shul's name, what this page is, and the way to the other two. The app throws all of
    it away on load.

    No times in it. Those come out of published.json and change every week, and a shell
    saying last season's mincha would be worse than a shell saying none.
    """
    others = [
        (n, ROUTES[n]["heading"]) for n in ROUTES if n != name
    ]
    links = "\n".join(
        f'      <a class="luach-item" href="/{n}/"><span class="luach-item-title">{h}</span></a>'
        for n, h in others
    )
    # The same Donate the app puts in the bar, and left off the donation page's own bar the
    # same way, so the frame before the app takes over is the page arriving rather than a
    # button appearing a moment later. The heart is backBar's, copied rather than shared
    # because this file cannot import from a JS module.
    give = "" if name == "donate" else (
        '\n    <a class="luach-bar-give" href="/donate/">'
        '<svg class="luach-bar-give-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
        ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
        '<path d="M12 20.3s-7.6-4.6-7.6-9.7A4.4 4.4 0 0 1 12 7.6a4.4 4.4 0 0 1 7.6 3c0 5.1-7.6 9.7-7.6 9.7z"/>'
        '</svg>Donate</a>'
    )
    return f"""<main id="main">
  <div class="luach-bar no-print">
    <a class="luach-back" href="/">&larr; Menu</a>
    <h1 class="luach-bar-title">{meta['heading']}</h1>{give}
  </div>
  <div class="luach-home">
    <p class="luach-intro">
      {meta['blurb']}
      <span lang="he">קהל לב מנחם</span>, 44 Coles Way, Lakewood, NJ 08701.
    </p>
    <nav class="luach-menu">
{links}
    </nav>
    <div class="luach-footer">
      <p class="luach-foot">Bais Medrash of Lakewood Commons 44 Coles Way Lakewood, NJ 08701</p>
    </div>
  </div>
</main>"""


def write_sitemap():
    """The sitemap, and the line in robots.txt that points at it.

    Four entries now that the three pages are real addresses rather than hashes on one.
    Written from the same ROUTES table the pages themselves are, so a page cannot be
    added without turning up here.
    """
    entries = "".join(
        f"  <url><loc>{SITE_URL}/{name}/</loc></url>\n" for name in ROUTES
    )
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by build-offline.py from SITE_URL, do not edit by hand. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"  <url><loc>{SITE_URL}/</loc></url>\n"
        f"{entries}"
        "</urlset>\n",
        encoding="utf-8",
        newline="\n",
    )
    robots = (ROOT / "robots.txt").read_text(encoding="utf-8")
    line = f"Sitemap: {SITE_URL}/sitemap.xml"
    robots = re.sub(r"^Sitemap: .*$", line, robots, flags=re.M)
    if "Sitemap:" not in robots:
        robots = robots.rstrip("\n") + "\n\n" + line + "\n"
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8", newline="\n")


def stamp_js_versions(page: Path, prefix: str, entry: str):
    """Give every JS module a content hash in its URL, via an import map.

    Same 10-minute GitHub Pages cache as the CSS, but the modules can't be stamped the
    same way: they import each other by relative path, so putting ?v= on the entry
    doesn't reach anything it pulls in. That bit us for real - a fix that lived in JS
    while its matching CSS shipped stamped meant phones ran new CSS against old JS and
    showed the wrong thing, which reads as "the fix didn't work".

    An import map rewrites those relative specifiers at load time without touching a
    single source file: `import './storage.js'` still resolves to /js/storage.js, and
    the map turns that into /js/storage.js?v=<hash>. The keys are site-absolute, so the
    same map works from the root page and from /admin/ alike. The entry itself is
    stamped directly, since a map applies to imports, not to <script src>.
    """
    html = page.read_text(encoding="utf-8")

    def digest(path):
        return hashlib.md5(path.read_bytes()).hexdigest()[:8]

    imports = {f"/js/{rel_key(f)}": f"/js/{rel_key(f)}?v={digest(f)}" for f in all_js_files()}
    block = f'{JS_MAP_MARKER}\n<script type="importmap">{json.dumps({"imports": imports})}</script>'

    existing = re.compile(re.escape(JS_MAP_MARKER) + r'\n<script type="importmap">.*?</script>', re.S)
    if existing.search(html):
        html = existing.sub(lambda m: block, html)
    else:
        html = html.replace("</head>", block + "\n</head>")
    html = re.sub(
        r'src="(?:\.\./)?js/' + re.escape(entry) + r'(?:\?v=[0-9a-f]+)?"',
        lambda m: f'src="{prefix}js/{entry}?v={digest(JS_DIR / entry)}"',
        html,
    )
    page.write_text(html, encoding="utf-8", newline="\n")


def main():
    files = all_js_files()
    texts, deps = build_dep_graph(files)
    order = topo_sort(deps)
    all_exports = {key: export_names(text) for key, text in texts.items()}

    chunks = []
    trailing_namespace_consts = []
    for key in order:
        if key == "data-loader.js":
            chunks.append(f"// ==== {key} (replaced: inlined data, no fetch) ====\n" + build_data_loader_replacement())
            continue
        body, ns_consts = transform_module(key, texts[key], all_exports)
        chunks.append(f"// ==== {key} ====\n{body}")
        trailing_namespace_consts.extend(ns_consts)

    # Namespace-object consts (from `import * as X`) are safe to declare anywhere
    # before the app actually starts running (see build-offline.py's module
    # docstring) - putting them all together right before app.js keeps the output
    # readable without needing per-file interleaving.
    entry_idx = order.index(ENTRY)
    check_name_collisions(order[: entry_idx + 1], texts)
    bundle = "\n\n".join(chunks[:entry_idx]) + "\n\n// ==== namespace shims for `import * as X` ====\n" + "\n".join(sorted(set(trailing_namespace_consts))) + "\n\n" + chunks[entry_idx]

    OUT_DIR.mkdir(exist_ok=True)
    # Site-absolute paths are for the hosted site; file:// has no site root.
    bundle = bundle.replace("'/assets/", "'assets/").replace('"/assets/', '"assets/')
    (OUT_DIR / "bundle.js").write_text(bundle, encoding="utf-8")

    # The congregation's page at the root, and the app under /admin.
    stamp_css_versions(ROOT / "index.html", "")
    stamp_js_versions(ROOT / "index.html", "", "luach.js")
    # Only the congregation's page: /admin is asked out of search, so an address for it in
    # a sitemap or a canonical tag would be working against that.
    stamp_site_url(ROOT / "index.html")
    # After the stamping, so the three pages carry the hashes just written into the menu.
    write_route_pages()
    write_sitemap()
    stamp_css_versions(ROOT / "admin" / "index.html", "../")
    stamp_js_versions(ROOT / "admin" / "index.html", "../", "app.js")

    # The offline copy is the app, not the luach: a USB stick is for making sheets, and
    # the luach needs a published file it has no way to fetch under file://. One plain
    # script off the filesystem, so the import map and the ?v= come straight back out,
    # and the site-absolute asset paths go back to relative ones.
    html = (ROOT / "admin" / "index.html").read_text(encoding="utf-8")
    html = html.replace('href="../css/', 'href="css/').replace('src="/assets/', 'src="assets/')
    # The block admin/index.html marks off with <!-- icons --> ... <!-- /icons -->.
    html = re.sub(r"[ \t]*<!-- icons -->.*?<!-- /icons -->\n", "", html, flags=re.S)
    if "webmanifest" in html:
        raise RuntimeError("offline build: the icon links were left in")
    # And the block it marks off with <!-- pdf --> ... <!-- /pdf -->: the two vendored
    # libraries behind the PDF button. Two thirds of a megabyte of third-party code that a
    # USB stick for making sheets has no use for, and the button is there for a phone that
    # will not print at the right size, which is not a problem this copy has. The app asks
    # pdfReady() before offering the button, so with them gone it simply is not there.
    html = re.sub(r"[ \t]*<!-- pdf -->.*?<!-- /pdf -->\n", "", html, flags=re.S)
    if "jspdf" in html or "html2canvas" in html:
        raise RuntimeError("offline build: the PDF libraries were left in")
    html = re.sub(re.escape(JS_MAP_MARKER) + r'\n<script type="importmap">.*?</script>\n', "", html, flags=re.S)
    html = re.sub(
        r'<script type="module" src="(?:\.\./)?js/' + re.escape(ENTRY) + r'(?:\?v=[0-9a-f]+)?"></script>',
        '<script src="bundle.js"></script>',
        html,
    )
    if "bundle.js" not in html:
        raise RuntimeError("offline build: failed to swap the module entry for bundle.js")
    (OUT_DIR / "index.html").write_text(html, encoding="utf-8")

    # rglob + mkdir so subdirectories come across too (assets/fonts/) - a flat glob
    # copied only top-level files and choked the moment a folder appeared.
    assets_out = OUT_DIR / "assets"
    assets_out.mkdir(exist_ok=True)
    for f in (ROOT / "assets").rglob("*"):
        if not f.is_file():
            continue
        dest = assets_out / f.relative_to(ROOT / "assets")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(f.read_bytes())

    css_out = OUT_DIR / "css"
    css_out.mkdir(exist_ok=True)
    for f in (ROOT / "css").glob("*.css"):
        (css_out / f.name).write_text(inline_fonts(f.read_text(encoding="utf-8")), encoding="utf-8")

    print(f"Built {OUT_DIR} ({len(order)} modules, {len(bundle.splitlines())} lines)")


if __name__ == "__main__":
    main()
