#!/usr/bin/env python3
"""Builds a fully offline, dependency-free copy of the app into offline/ -
no ES modules, no fetch(), nothing that requires a local server: just
double-click offline/index.html (via file://) in any modern browser, so it
can be copied to a USB drive and run on a computer with no internet access.

How it works:
  - Every js/**/*.js module is concatenated into one plain <script> (no
    type="module"), in dependency order. `export` is stripped (everything
    becomes a normal top-level declaration in one shared scope - verified
    there are no name collisions across modules) and `import {a,b} from`
    lines are dropped entirely, since after flattening the names already
    exist. `import * as X from '...'` becomes a generated `const X = {...}`
    object built from that module's own export names.
  - The four data/*.json lookup tables are inlined as JS constants and
    data-loader.js's fetch()-based loadTables() is replaced with a version
    that just returns them directly - fetch() of local files is blocked
    under file:// in most browsers, same reason ES modules are.
  - assets/ is copied alongside index.html (plain <img src="..."> to a
    relative file works fine under file://, unlike fetch/modules). The
    Hebrew webfont is the exception: a font file is subject to CORS even
    from file://, so it's inlined into the CSS as a data: URI instead.

Re-run this any time the js/ source changes to refresh offline/.
"""
import base64
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
JS_DIR = ROOT / "js"
OUT_DIR = ROOT / "offline"
ENTRY = "app.js"
JS_MAP_MARKER = "<!-- js version map: generated by build-offline.py, do not edit by hand -->"

EXPORT_FUNC_RE = re.compile(r"^export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)", re.M)
EXPORT_CONST_RE = re.compile(r"^export\s+const\s+([A-Za-z0-9_]+)", re.M)
IMPORT_NAMED_RE = re.compile(r"^import\s*\{[^}]*\}\s*from\s*['\"][^'\"]+['\"];?\s*$", re.M)
IMPORT_STAR_RE = re.compile(r"^import\s*\*\s*as\s+([A-Za-z0-9_]+)\s*from\s*['\"]([^'\"]+)['\"];?\s*$", re.M)


def all_js_files():
    return sorted(JS_DIR.rglob("*.js"))


def rel_key(path: Path) -> str:
    return path.relative_to(JS_DIR).as_posix()


def resolve_import(from_file: Path, spec: str) -> str:
    resolved = (from_file.parent / spec).resolve()
    return rel_key(resolved)


def export_names(text: str) -> list:
    return EXPORT_FUNC_RE.findall(text) + EXPORT_CONST_RE.findall(text)


def build_dep_graph(files):
    texts = {rel_key(f): f.read_text(encoding="utf-8") for f in files}
    deps = {}
    for key, text in texts.items():
        f = JS_DIR / key
        d = set()
        for m in IMPORT_NAMED_RE.finditer(text):
            spec = re.search(r"from\s*['\"]([^'\"]+)['\"]", m.group(0)).group(1)
            d.add(resolve_import(f, spec))
        for m in IMPORT_STAR_RE.finditer(text):
            d.add(resolve_import(f, m.group(2)))
        deps[key] = d
    return texts, deps


def topo_sort(deps):
    order = []
    visited = set()
    temp = set()

    def visit(key):
        if key in visited:
            return
        if key in temp:
            raise RuntimeError(f"circular dependency at {key}")
        temp.add(key)
        for d in sorted(deps.get(key, [])):
            visit(d)
        temp.discard(key)
        visited.add(key)
        order.append(key)

    for key in sorted(deps):
        visit(key)
    return order


def transform_module(key, text, all_exports):
    # Record namespace-import requests, then strip all import lines.
    namespace_consts = []
    for m in IMPORT_STAR_RE.finditer(text):
        local_name, spec = m.group(1), m.group(2)
        target = resolve_import(JS_DIR / key, spec)
        names = all_exports[target]
        namespace_consts.append(f"const {local_name} = {{ {', '.join(names)} }};")
    text = IMPORT_STAR_RE.sub("", text)
    text = IMPORT_NAMED_RE.sub("", text)
    # Strip the `export ` keyword, leaving the declaration itself.
    text = re.sub(r"^export\s+(?=(async\s+)?function\s)", "", text, flags=re.M)
    text = re.sub(r"^export\s+(?=const\s)", "", text, flags=re.M)
    return text.strip("\n"), namespace_consts


def build_data_loader_replacement():
    tables = {}
    for name, filename in [
        ("parshaChutz", "parsha_chutz.json"),
        ("parshaEY", "parsha_ey.json"),
        ("parshaNames", "parsha_names.json"),
        ("specialDays", "special_days.json"),
    ]:
        tables[name] = json.loads((ROOT / "data" / filename).read_text(encoding="utf-8"))
    lines = ["// --- inlined data/*.json (offline build: fetch() of local files is blocked under file://) ---"]
    for name, data in tables.items():
        lines.append(f"const __TABLE_{name} = {json.dumps(data, ensure_ascii=False)};")
    lines.append("let cached = null;")
    lines.append("async function loadTables() {")
    lines.append("  if (cached) return cached;")
    lines.append("  cached = { parshaChutz: __TABLE_parshaChutz, parshaEY: __TABLE_parshaEY, parshaNames: __TABLE_parshaNames, specialDays: __TABLE_specialDays };")
    lines.append("  return cached;")
    lines.append("}")
    return "\n".join(lines)


def inline_fonts(css: str) -> str:
    """Replace url(../assets/fonts/x.woff2) with a base64 data: URI.

    Chrome treats a font fetched from file:// as cross-origin and refuses to use it, so
    the copied .woff2 files would be ignored in exactly the offline case they exist for.
    A data: URI is part of the stylesheet itself, so there is no fetch to block. The two
    Hebrew subsets are ~25KB total, small enough that inlining costs nothing.
    """

    def sub(match):
        path = ROOT / "assets" / "fonts" / match.group(1)
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        return f"url('data:font/woff2;base64,{b64}')"

    return re.sub(r"url\('\.\./assets/fonts/([\w.-]+)'\)", sub, css)


def stamp_css_versions():
    """Rewrite index.html's stylesheet links to css/x.css?v=<hash of that file>.

    GitHub Pages serves everything with a 10-minute max-age, so after a deploy the
    browser keeps showing the previous stylesheet until it expires - a design change
    looks like it simply didn't ship. The hash changes only when the CSS does, so the
    new URL is fetched immediately while an unchanged file stays cached.

    See stamp_js_versions() for the modules, which need a different mechanism.
    """
    html = (ROOT / "index.html").read_text(encoding="utf-8")

    def stamp(match):
        name = match.group(1)
        digest = hashlib.md5((ROOT / "css" / name).read_bytes()).hexdigest()[:8]
        return f'href="css/{name}?v={digest}"'

    stamped = re.sub(r'href="css/([\w.-]+\.css)(?:\?v=[0-9a-f]+)?"', stamp, html)
    if stamped != html:
        (ROOT / "index.html").write_text(stamped, encoding="utf-8", newline="\n")


def stamp_js_versions():
    """Give every JS module a content hash in its URL, via an import map.

    Same 10-minute GitHub Pages cache as the CSS, but the modules can't be stamped the
    same way: they import each other by relative path, so putting ?v= on the entry
    doesn't reach anything it pulls in. That bit us for real - a fix that lived in JS
    while its matching CSS shipped stamped meant phones ran new CSS against old JS and
    showed the wrong thing, which reads as "the fix didn't work".

    An import map rewrites those relative specifiers at load time without touching a
    single source file: `import './storage.js'` still resolves to /js/storage.js, and
    the map turns that into /js/storage.js?v=<hash>. The map lives in index.html, which
    a page load revalidates anyway - the same reason the CSS stamps work. The entry
    itself is stamped directly, since a map applies to imports, not to <script src>.
    """
    html = (ROOT / "index.html").read_text(encoding="utf-8")

    def digest(path):
        return hashlib.md5(path.read_bytes()).hexdigest()[:8]

    imports = {f"./js/{rel_key(f)}": f"./js/{rel_key(f)}?v={digest(f)}" for f in all_js_files()}
    block = f'{JS_MAP_MARKER}\n<script type="importmap">{json.dumps({"imports": imports})}</script>'

    existing = re.compile(re.escape(JS_MAP_MARKER) + r'\n<script type="importmap">.*?</script>', re.S)
    if existing.search(html):
        html = existing.sub(lambda m: block, html)
    else:
        html = html.replace("</head>", block + "\n</head>")
    html = re.sub(
        r'src="js/' + re.escape(ENTRY) + r'(?:\?v=[0-9a-f]+)?"',
        lambda m: f'src="js/{ENTRY}?v={digest(JS_DIR / ENTRY)}"',
        html,
    )

    (ROOT / "index.html").write_text(html, encoding="utf-8", newline="\n")


def main():
    files = all_js_files()
    texts, deps = build_dep_graph(files)
    order = topo_sort(deps)
    all_exports = {key: export_names(text) for key, text in texts.items()}

    chunks = []
    trailing_namespace_consts = []
    for key in order:
        if key == "data-loader.js":
            chunks.append(f"// ==== {key} (replaced: inlined data, no fetch) ====\n" + build_data_loader_replacement())
            continue
        body, ns_consts = transform_module(key, texts[key], all_exports)
        chunks.append(f"// ==== {key} ====\n{body}")
        trailing_namespace_consts.extend(ns_consts)

    # Namespace-object consts (from `import * as X`) are safe to declare anywhere
    # before the app actually starts running (see build-offline.py's module
    # docstring) - putting them all together right before app.js keeps the output
    # readable without needing per-file interleaving.
    entry_idx = order.index(ENTRY)
    bundle = "\n\n".join(chunks[:entry_idx]) + "\n\n// ==== namespace shims for `import * as X` ====\n" + "\n".join(sorted(set(trailing_namespace_consts))) + "\n\n" + chunks[entry_idx]

    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "bundle.js").write_text(bundle, encoding="utf-8")

    stamp_css_versions()
    stamp_js_versions()

    # The offline copy is one plain script off the filesystem: no modules to remap, and
    # no cache to bust either, so both the import map and the ?v= come straight back out.
    html = (ROOT / "index.html").read_text(encoding="utf-8")
    html = re.sub(re.escape(JS_MAP_MARKER) + r'\n<script type="importmap">.*?</script>\n', "", html, flags=re.S)
    html = re.sub(
        r'<script type="module" src="js/' + re.escape(ENTRY) + r'(?:\?v=[0-9a-f]+)?"></script>',
        '<script src="bundle.js"></script>',
        html,
    )
    if "bundle.js" not in html:
        raise RuntimeError("offline build: failed to swap the module entry for bundle.js")
    (OUT_DIR / "index.html").write_text(html, encoding="utf-8")

    # rglob + mkdir so subdirectories come across too (assets/fonts/) - a flat glob
    # copied only top-level files and choked the moment a folder appeared.
    assets_out = OUT_DIR / "assets"
    assets_out.mkdir(exist_ok=True)
    for f in (ROOT / "assets").rglob("*"):
        if not f.is_file():
            continue
        dest = assets_out / f.relative_to(ROOT / "assets")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(f.read_bytes())

    css_out = OUT_DIR / "css"
    css_out.mkdir(exist_ok=True)
    for f in (ROOT / "css").glob("*.css"):
        (css_out / f.name).write_text(inline_fonts(f.read_text(encoding="utf-8")), encoding="utf-8")

    print(f"Built {OUT_DIR} ({len(order)} modules, {len(bundle.splitlines())} lines)")


if __name__ == "__main__":
    main()
