const {chromium}=require('playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.DISPLAY_TEST_URL||'http://127.0.0.1:8797';
const api=async(path,method='GET',body)=>{const r=await fetch(base+'/api/display/admin/'+path,{method,headers:{'Content-Type':'application/json',Origin:base,'X-Display-Request':'1'},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(JSON.stringify(v));return v;};
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1920,height:1080},colorScheme:'dark'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const original=await api('appearance');const out='../../../outputs/tv-themes';fs.mkdirSync(out,{recursive:true});try{
 await api('appearance','PUT',{...original,mode:'light'});
 await page.goto(base+'/display/');await page.waitForSelector('.tv-panel');await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('.tv-stage').getAttribute('data-theme'),'light');
 const snapshot=await api('preview','POST',{at:'2026-09-23T16:00:00Z'});
 await page.evaluate(async snapshot=>{const {DisplayView}=await import('/display-assets/renderer.js');document.body.innerHTML='<div id="test" style="position:relative;width:100vw;height:100vh"></div>';window.v=new DisplayView(document.querySelector('#test'));window.snap=snapshot;const common={startsAt:'2026-09-23T00:00:00Z',endsAt:null};snapshot.items=[{...common,id:'sample1',kind:'announcement',title:'DEVELOPMENT SAMPLE',data:{message:'Community notices appear here. תזכורת לקהילה',priority:'important',placement:'left',behavior:'pinned',duration:25}},{...common,id:'sample2',kind:'announcement',title:'Preview reminder',data:{message:'Sample only. Approved announcements use the same display.',priority:'urgent',placement:'left',duration:25}},{...common,id:'sample3',kind:'dedication',data:{dedicationType:'לזכות',dedicationName:'דוגמה לתצוגה בלבד',dedicationText:'DEVELOPMENT SAMPLE ONLY',sponsor:'Preview only',duration:25}}];v.update(snapshot,{preview:true,now:1000,theme:'light'});},snapshot);
 await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:out+'/light-1920.png'});
 const before=await page.evaluate(()=>{window.panel=v.stage.querySelector('.tv-panel');return {html:v.lastRender,slots:JSON.stringify([...v.slots]),sizes:[...v.stage.querySelectorAll('.tv-panel,.tv-card')].map(e=>[e.clientWidth,e.clientHeight])}});
 await page.evaluate(()=>v.update(snap,{preview:true,now:1000,theme:'dark'}));
 const after=await page.evaluate(()=>({same:window.panel===v.stage.querySelector('.tv-panel'),html:v.lastRender,slots:JSON.stringify([...v.slots]),sizes:[...v.stage.querySelectorAll('.tv-panel,.tv-card')].map(e=>[e.clientWidth,e.clientHeight]),overflow:[...v.stage.querySelectorAll('.tv-panel,.tv-card')].some(e=>e.scrollHeight>e.clientHeight+2)}));
 assert.equal(after.same,true);assert.equal(after.html,before.html);assert.equal(after.slots,before.slots);assert.deepEqual(after.sizes,before.sizes);assert.equal(after.overflow,false);await page.screenshot({path:out+'/dark-1920.png'});
 await page.evaluate(()=>{snap.appearance={mode:'scheduled',darkStart:'19:00',lightStart:'07:00'};snap.at='2026-09-24T00:00:00Z';v.update(snap,{preview:true});});assert.equal(await page.locator('.tv-stage').getAttribute('data-theme'),'dark');
 await page.goto(base+'/display/');await page.waitForSelector('.tv-panel');const saved=await api('appearance');await api('appearance','PUT',{...saved,mode:'dark'});await page.waitForFunction(()=>document.querySelector('.tv-stage')?.dataset.theme==='dark',{},{timeout:20000});await page.context().setOffline(true);await page.waitForTimeout(1200);assert.equal(await page.locator('.tv-stage').getAttribute('data-theme'),'dark');await page.context().setOffline(false);
 await page.goto(base+'/admin/display/');await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.waitForSelector('#appearance-preview .tv-panel');await page.getByRole('button',{name:'Preview Light',exact:true}).click();assert.equal(await page.locator('.tv-stage').getAttribute('data-theme'),'light');assert.equal((await api('appearance')).mode,'dark');await page.getByRole('button',{name:'Preview Dark',exact:true}).click();await page.screenshot({path:out+'/appearance-admin.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/appearance-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('Theme rendering, unchanged DOM/layout/rotation, automatic update, offline retention, unsaved previews and mobile checks passed.');
}finally{const current=await api('appearance');await api('appearance','PUT',{...original,version:current.version});await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
